services:
  db:
    container_name: postgres
    image: postgres:15.7-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello_web_dev

volumes:
  postgres:
